[build]
builder = "nixpacks"
buildCommand = "echo 'Building with nixpacks'"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "frontend"
source = "frontend"

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.prod"

[services.variables]
NODE_ENV = "production"
VITE_API_URL = "${{backend.RAILWAY_PUBLIC_DOMAIN}}/api"

[[services]]
name = "backend"
source = "backend"

[services.build]
builder = "DOCKERFILE" 
dockerfilePath = "Dockerfile.prod"

[services.variables]
NODE_ENV = "production"
PORT = "3001"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
JWT_SECRET = "${{JWT_SECRET}}"
CORS_ORIGIN = "${{frontend.RAILWAY_PUBLIC_DOMAIN}}"